#!/bin/sh
PART=${DELPHI_INCVER_PART:-patch}
pwsh -NoProfile -Command "
  \$result = Invoke-DelphiIncVer \`
    -File 'source/delphi-incver.ps1' \`
    -IncverTarget 'Text' \`
    -IncverStyle 'SemVer' \`
    -IncverPart '$PART' \`
    -IncverPattern '(\d+\.\d+\.\d+)'
  if (-not \$result.Success) { exit 1 }
"
git add source/delphi-incver.ps1
